/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export interface PgcArtworks {
  aspect_ratio: Generated<number | null>;
  created_at: number;
  deleted_at: number | null;
  id: Generated<number>;
  media_url: string;
  title: string;
  type: string;
  updated_at: number;
  url: string;
  version: Generated<number>;
}

export interface Posts {
  content: string;
  created_at: number;
  deleted_at: number | null;
  id: Generated<number>;
  published_at: number | null;
  status: Generated<string>;
  title: string;
  updated_at: number;
  user_id: number;
  version: Generated<number>;
  view_count: Generated<number>;
}

export interface StatsTracks {
  created_at: number;
  event: string;
  id: Generated<number>;
  platform: string;
  source: string;
  user_id: number | null;
}

export interface SystemSettings {
  key: string;
  updated_at: number;
  value: string;
}

export interface UgcPosters {
  answers: Json;
  created_at: number;
  poster_id: string;
  result_name: string;
  result_type: number;
  status: Generated<string>;
  updated_at: number;
  user_id: number | null;
}

export interface UgcQuestions {
  created_at: number;
  id: number;
  options: Json;
  text: string;
  updated_at: number;
}

export interface Users {
  avatar_url: string | null;
  created_at: number;
  deleted_at: number | null;
  email: string;
  id: Generated<number>;
  inviter_code: number | null;
  nickname: string | null;
  openid: string | null;
  password: string;
  role: Generated<string | null>;
  updated_at: number;
  username: string;
  version: Generated<number>;
}

export interface DB {
  pgc_artworks: PgcArtworks;
  posts: Posts;
  stats_tracks: StatsTracks;
  system_settings: SystemSettings;
  ugc_posters: UgcPosters;
  ugc_questions: UgcQuestions;
  users: Users;
}
